apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-prometheus
  template:
    metadata:
      labels:
        app: demo-prometheus
    spec:
      containers:
        - name: demo-prometheus
          image: farhanluckali/demo-prometheus:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-prometheus-service
  labels:
    app: demo-prometheus
spec:
  selector:
    app: demo-prometheus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
  type: NodePort
