apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-prometheus-service
  labels:
    release: prometheus #This label allows Prometheus to find service monitors in the cluster and register them.
spec:
  selector:
    matchLabels:
      app: demo-prometheus
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 30s
    
    